server:
  servlet:
    context-path: "/security"
  port: 8082

resources:
  base:
    location: "./resources/"

new-capture:
    file-name: "new_capture"
    annotated:
      file-name: "test_new_capture_annotated"

yolo:
  person-detector:
    base:
      location: "./yolo"
    threshold:
      confidence: 0.5
      non_maxima_suppression: 0.3

spring:
  rabbitmq:
    port: 5672
    host: rabbitmq
  cloud:
    stream:
      bindings:
        output:
          destination: updated.security-config